image: python:3.9

stages:
  - lint
  - test


before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry cache:clear --all pypi
  - poetry install --no-interaction --no-root

Run linter:
  stage: lint
  script:
    - poetry run python -m black --check comparer tests
    - poetry run python -m autoflake \
      --check --recursive --remove-all-unused-imports --expand-star-imports \
      comparer tests
    - poetry run python -m isort --check-only comparer tests
    - poetry run python -m mypy comparer tests
    - poetry run python -m bandit --configfile .bandit.yaml --recursive comparer tests

Run tests:
  stage: test
  script:
    - source .venv/bin/activate
    - poetry run python -m pytest tests/
